---
- name: TXT | set vars
  ansible.builtin.set_fact:
    ttl: "{{ rec.ttl | default(nsupdate_default_ttl) }}"
    qname: "{{ (rec.name | default('@')) == '@'
               | ternary(zone_name, rec.name ~ '.' ~ zone_name) }}"
    want: "\"{{ rec.text }}\""

- name: TXT | current?
  ansible.builtin.command: dig +short TXT {{ qname }} @127.0.0.1
  register: dig_txt
  changed_when: false

- name: TXT | write update
  when: want not in dig_txt.stdout
  ansible.builtin.copy:
    dest: "/tmp/u-txt-{{ rec.name | default('root') }}.txt"
    owner: root
    group: root
    mode: "0600"
    content: |
      server {{ nsupdate_server }}
      zone {{ zone_name }}
      update delete {{ qname }} TXT
      update add {{ qname }} {{ ttl }} TXT "{{ rec.text }}"
      send

- name: TXT | apply update
  when: want not in dig_txt.stdout
  ansible.builtin.command: nsupdate -k {{ nsupdate_keyfile }} -v /tmp/u-txt-{{ rec.name | default('root') }}.txt
  changed_when: true
